#spring:
#  datasource:
#    url: mysql://root:msiDXy9uXwEuRuDj2gxh@containers-us-west-157.railway.app:5993/railway
#    username: root
#    password: msiDXy9uXwEuRuDj2gxh
#    name: railway
#
#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes